name: Compile
on:
  push:
    paths-ignore:
      - "README.md" # don't bother if README is the only thing that's changed
  pull_request:
    paths-ignore:
      - "README.md" # don't bother if README is the only thing that's changed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: main
        submodules: true
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install other dependencies
      run: sudo apt-get update && sudo apt-get install --assume-yes wine-stable wine64
    - name: Install makelove
      run:
        pip3 install git+https://github.com/pfirsich/makelove/
    - name: Build
      run: cd main && python3 -m makelove
    - name: Prepare Artifact Names
      run: |
        echo "ARTIFACT_NAME_LOVE=$(ls main/makelove-build/love | head -n1)" >> $GITHUB_ENV
        echo "ARTIFACT_NAME_APPIMAGE=$(ls main/makelove-build/appimage | head -n1)" >> $GITHUB_ENV
        echo "ARTIFACT_NAME_WIN64=$(ls main/makelove-build/win64 | head -n1)" >> $GITHUB_ENV
        echo "ARTIFACT_NAME_MACOS=$(ls main/makelove-build/macos | head -n1)" >> $GITHUB_ENV
    - name: Artifact (LÖVE)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME_LOVE }}
        path: main/makelove-build/love/${{ env.ARTIFACT_NAME_LOVE }}
    - name: Artifact (AppImage)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME_APPIMAGE }}
        path: main/makelove-build/appimage/${{ env.ARTIFACT_NAME_APPIMAGE }}
    - name: Artifact (Win64)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME_WIN64 }}
        path: main/makelove-build/win64/${{ env.ARTIFACT_NAME_WIN64 }}
    - name: Artifact (MacOS)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME_MACOS }}
        path: main/makelove-build/macos/${{ env.ARTIFACT_NAME_MACOS }}
